tokenizer: tester.o tokenizer.o history.o
	   cc -o tokenizer tester.o tokenizer.o history.o

mainui: mainui.o tokenizer.o history.o
	   cc -o tokenizer mainui.o tokenizer.o history.o

clean:
	   rm -f *.o tokenizer mainui
